name: Ernesto
favicon: null
layout_spectrum: 0.25723
typography_spectrum: 0.14065
title: null
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#dbdfe8'
    - '#1b6aa3'
    - '#0d0b0c'
    - '#bc7e71'
    - '#604439'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
